
<FinancesScreenView>
    BoxLayout:
        orientation: 'vertical'


        MDTopAppBar:
            title: "Finanzen"
            right_action_items: [["dots-vertical", lambda x: root.on_settings_pressed()]]

        MDBoxLayout:
            orientation: "horizontal"
            spacing: 5
            padding: 5

            MDRaisedButton:
                size_hint: (1, None)
                text: "Abbruch"
                on_release:
                    root.on_cancel_pressed()

